[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_todo_list = "6aWv5V6DNuDGCZciWpL2RHj315z5vL5DhaTyV3Pj4hB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/quanta/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
